data:
  iemocap: &iemocap
    name: iemocap
    path: '../other_tts_data/IEMOCAP_full_release/Session'
    test_spk: 1
    save_manifest: test_spk_
  
use_data: *iemocap


num_samples: 5
load_chk: false
infer: false
chk: 'default.pt'
device: cuda:1
exp_name: base
model: fastspeech   #fastspeech
fs_config: 'config/fastspeech.yaml'
num_epochs: 2
freq: 50
batch_size: 24
lr: 0.001
weight_decay: 1e-6
bypass_checkpoint: true


wandb_project: emo_recog
notes: none
tags: none
num_samples: 4
disable: true